# Form implementation generated from reading ui file 'D:\Retail-Management-Project\ui\BillingSystem.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1629, 860)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/teddy-bear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(110, 88, 165);")
        self.label.setObjectName("label")
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setGeometry(QtCore.QRect(70, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogout.setFont(font)
        self.pushButtonLogout.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/log-out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogout.setIcon(icon1)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 50, 611, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(247, 79, 164);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 1591, 801))
        self.label_5.setStyleSheet("border-radius: 20; background: rgb(255, 255, 255)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 1631, 861))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/background.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 50, 21, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/account.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.timelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(1280, 60, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.timelabel.setFont(font)
        self.timelabel.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.timelabel.setText("")
        self.timelabel.setObjectName("timelabel")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 180, 1541, 80))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEditBillNo = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditBillNo.setGeometry(QtCore.QRect(100, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEditBillNo.setFont(font)
        self.lineEditBillNo.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;")
        self.lineEditBillNo.setPlaceholderText("")
        self.lineEditBillNo.setObjectName("lineEditBillNo")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(560, 40, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(1100, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_8.setObjectName("label_8")
        self.lineEditCustomerName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCustomerName.setGeometry(QtCore.QRect(710, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEditCustomerName.setFont(font)
        self.lineEditCustomerName.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;")
        self.lineEditCustomerName.setPlaceholderText("")
        self.lineEditCustomerName.setObjectName("lineEditCustomerName")
        self.lineEditContactNo = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditContactNo.setGeometry(QtCore.QRect(1220, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEditContactNo.setFont(font)
        self.lineEditContactNo.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;")
        self.lineEditContactNo.setPlaceholderText("")
        self.lineEditContactNo.setObjectName("lineEditContactNo")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSearch.setGeometry(QtCore.QRect(410, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/search (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon2)
        self.pushButtonSearch.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.groupBoxProducts = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxProducts.setGeometry(QtCore.QRect(50, 280, 661, 431))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBoxProducts.setFont(font)
        self.groupBoxProducts.setObjectName("groupBoxProducts")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBoxProducts)
        self.label_9.setGeometry(QtCore.QRect(20, 45, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBoxProducts)
        self.label_10.setGeometry(QtCore.QRect(20, 115, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBoxProducts)
        self.label_11.setGeometry(QtCore.QRect(20, 195, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_11.setObjectName("label_11")
        self.comboBoxCategory = QtWidgets.QComboBox(parent=self.groupBoxProducts)
        self.comboBoxCategory.setGeometry(QtCore.QRect(20, 80, 601, 31))
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.comboBoxSubcategory = QtWidgets.QComboBox(parent=self.groupBoxProducts)
        self.comboBoxSubcategory.setGeometry(QtCore.QRect(20, 150, 601, 31))
        self.comboBoxSubcategory.setObjectName("comboBoxSubcategory")
        self.comboProduct = QtWidgets.QComboBox(parent=self.groupBoxProducts)
        self.comboProduct.setGeometry(QtCore.QRect(20, 230, 601, 31))
        self.comboProduct.setObjectName("comboProduct")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBoxProducts)
        self.label_12.setGeometry(QtCore.QRect(20, 275, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.label_12.setObjectName("label_12")
        self.pushButtonAddToCart = QtWidgets.QPushButton(parent=self.groupBoxProducts)
        self.pushButtonAddToCart.setGeometry(QtCore.QRect(60, 370, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddToCart.setFont(font)
        self.pushButtonAddToCart.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/add (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAddToCart.setIcon(icon3)
        self.pushButtonAddToCart.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonAddToCart.setObjectName("pushButtonAddToCart")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBoxProducts)
        self.pushButtonRemove.setGeometry(QtCore.QRect(270, 370, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRemove.setFont(font)
        self.pushButtonRemove.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon4)
        self.pushButtonRemove.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.groupBoxProducts)
        self.pushButtonClear.setGeometry(QtCore.QRect(450, 370, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/eraser.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClear.setIcon(icon5)
        self.pushButtonClear.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.groupBoxProducts)
        self.lineEditQuantity.setGeometry(QtCore.QRect(20, 310, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEditQuantity.setFont(font)
        self.lineEditQuantity.setStyleSheet("\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;")
        self.lineEditQuantity.setPlaceholderText("")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.groupBoxBillOptions = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxBillOptions.setGeometry(QtCore.QRect(50, 720, 661, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBoxBillOptions.setFont(font)
        self.groupBoxBillOptions.setObjectName("groupBoxBillOptions")
        self.pushButtonTotal = QtWidgets.QPushButton(parent=self.groupBoxBillOptions)
        self.pushButtonTotal.setGeometry(QtCore.QRect(40, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTotal.setFont(font)
        self.pushButtonTotal.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/sigma.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTotal.setIcon(icon6)
        self.pushButtonTotal.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonTotal.setObjectName("pushButtonTotal")
        self.pushButtonGenerate = QtWidgets.QPushButton(parent=self.groupBoxBillOptions)
        self.pushButtonGenerate.setGeometry(QtCore.QRect(190, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGenerate.setFont(font)
        self.pushButtonGenerate.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/idea.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonGenerate.setIcon(icon7)
        self.pushButtonGenerate.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonGenerate.setObjectName("pushButtonGenerate")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBoxBillOptions)
        self.pushButtonNew.setGeometry(QtCore.QRect(370, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNew.setFont(font)
        self.pushButtonNew.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNew.setIcon(icon8)
        self.pushButtonNew.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBoxBillOptions)
        self.pushButtonExit.setGeometry(QtCore.QRect(500, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon9)
        self.pushButtonExit.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.groupBoxBillWindow = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxBillWindow.setGeometry(QtCore.QRect(730, 280, 861, 541))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBoxBillWindow.setFont(font)
        self.groupBoxBillWindow.setObjectName("groupBoxBillWindow")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_14.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_15.setGeometry(QtCore.QRect(560, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_16.setGeometry(QtCore.QRect(560, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.labelCustomerName = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.labelCustomerName.setGeometry(QtCore.QRect(170, 50, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCustomerName.setFont(font)
        self.labelCustomerName.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.labelCustomerName.setText("")
        self.labelCustomerName.setObjectName("labelCustomerName")
        self.labelBillNo = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.labelBillNo.setGeometry(QtCore.QRect(110, 80, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelBillNo.setFont(font)
        self.labelBillNo.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.labelBillNo.setText("")
        self.labelBillNo.setObjectName("labelBillNo")
        self.labelDate = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.labelDate.setGeometry(QtCore.QRect(620, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDate.setFont(font)
        self.labelDate.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.labelPhone = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.labelPhone.setGeometry(QtCore.QRect(660, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPhone.setFont(font)
        self.labelPhone.setStyleSheet("color: rgb(72, 72, 72);\n"
"")
        self.labelPhone.setText("")
        self.labelPhone.setObjectName("labelPhone")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBoxBillWindow)
        self.tableWidget.setGeometry(QtCore.QRect(20, 110, 831, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setItem(1, 0, item)
        self.label_17 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_17.setGeometry(QtCore.QRect(540, 410, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_18.setGeometry(QtCore.QRect(520, 470, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_19.setGeometry(QtCore.QRect(520, 440, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBoxBillWindow)
        self.label_20.setGeometry(QtCore.QRect(550, 500, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEditTotal = QtWidgets.QLineEdit(parent=self.groupBoxBillWindow)
        self.lineEditTotal.setGeometry(QtCore.QRect(600, 400, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEditTotal.setFont(font)
        self.lineEditTotal.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;\n"
"color: rgb(247, 79, 164);")
        self.lineEditTotal.setText("")
        self.lineEditTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditTotal.setPlaceholderText("")
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.lineEditDiscount = QtWidgets.QLineEdit(parent=self.groupBoxBillWindow)
        self.lineEditDiscount.setGeometry(QtCore.QRect(600, 430, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEditDiscount.setFont(font)
        self.lineEditDiscount.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;\n"
"color: rgb(247, 79, 164);")
        self.lineEditDiscount.setText("")
        self.lineEditDiscount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditDiscount.setPlaceholderText("")
        self.lineEditDiscount.setObjectName("lineEditDiscount")
        self.lineEditPayment = QtWidgets.QLineEdit(parent=self.groupBoxBillWindow)
        self.lineEditPayment.setGeometry(QtCore.QRect(600, 460, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEditPayment.setFont(font)
        self.lineEditPayment.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;\n"
"color: rgb(247, 79, 164);")
        self.lineEditPayment.setText("")
        self.lineEditPayment.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditPayment.setPlaceholderText("")
        self.lineEditPayment.setObjectName("lineEditPayment")
        self.lineEditRest = QtWidgets.QLineEdit(parent=self.groupBoxBillWindow)
        self.lineEditRest.setGeometry(QtCore.QRect(600, 490, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEditRest.setFont(font)
        self.lineEditRest.setStyleSheet("border: none;\n"
"border-bottom: 2px solid grey; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"border-color: rgb(211, 211, 211);\n"
"padding: 5px;\n"
"color: rgb(247, 79, 164);")
        self.lineEditRest.setText("")
        self.lineEditRest.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditRest.setPlaceholderText("")
        self.lineEditRest.setObjectName("lineEditRest")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.pushButtonLogout.raise_()
        self.label_2.raise_()
        self.label_7.raise_()
        self.timelabel.raise_()
        self.groupBox.raise_()
        self.groupBoxProducts.raise_()
        self.groupBoxBillOptions.raise_()
        self.groupBoxBillWindow.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Billing System"))
        self.label.setText(_translate("MainWindow", "EMP00"))
        self.pushButtonLogout.setText(_translate("MainWindow", "Logout"))
        self.label_2.setText(_translate("MainWindow", "Billing System"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer Details: "))
        self.label_3.setText(_translate("MainWindow", "Bill No.: "))
        self.label_4.setText(_translate("MainWindow", "Customer Name:"))
        self.label_8.setText(_translate("MainWindow", "Contact No. :"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.groupBoxProducts.setTitle(_translate("MainWindow", "Products:"))
        self.label_9.setText(_translate("MainWindow", "Select Category:"))
        self.label_10.setText(_translate("MainWindow", "Sub Category:"))
        self.label_11.setText(_translate("MainWindow", "Product:"))
        self.label_12.setText(_translate("MainWindow", "Quantity:"))
        self.pushButtonAddToCart.setText(_translate("MainWindow", "Add to cart"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.groupBoxBillOptions.setTitle(_translate("MainWindow", "Bill Options:"))
        self.pushButtonTotal.setText(_translate("MainWindow", "Total"))
        self.pushButtonGenerate.setText(_translate("MainWindow", "Generate"))
        self.pushButtonNew.setText(_translate("MainWindow", "New"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.groupBoxBillWindow.setTitle(_translate("MainWindow", "Bill Window: "))
        self.label_13.setText(_translate("MainWindow", "Customer Name:"))
        self.label_14.setText(_translate("MainWindow", "Bill No. :"))
        self.label_15.setText(_translate("MainWindow", "Phone No. :"))
        self.label_16.setText(_translate("MainWindow", "Date: "))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Unit Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Amount"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(_translate("MainWindow", " Total:"))
        self.label_18.setText(_translate("MainWindow", "Payment:"))
        self.label_19.setText(_translate("MainWindow", "Discount:"))
        self.label_20.setText(_translate("MainWindow", "Rest:"))
