# Form implementation generated from reading ui file 'D:\Retail-Management-Project\ui\Employeemanagement.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1530, 772)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/teddy-bear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(104, 96, 171);")
        self.label.setObjectName("label")
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setGeometry(QtCore.QRect(70, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogout.setFont(font)
        self.pushButtonLogout.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/log-out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogout.setIcon(icon1)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 651, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(104, 96, 171);\n"
"font: bold 28pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBoxMenu = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxMenu.setGeometry(QtCore.QRect(50, 160, 401, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxMenu.setFont(font)
        self.groupBoxMenu.setObjectName("groupBoxMenu")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBoxMenu)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBoxMenu)
        self.pushButtonSearch.setGeometry(QtCore.QRect(230, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/search (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon2)
        self.pushButtonSearch.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.lineEditEmployeeID = QtWidgets.QLineEdit(parent=self.groupBoxMenu)
        self.lineEditEmployeeID.setGeometry(QtCore.QRect(30, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEditEmployeeID.setFont(font)
        self.lineEditEmployeeID.setStyleSheet("border: none;\n"
"border-bottom: 2px solid black; /* Điều chỉnh độ dày và màu của viền dưới */\n"
"padding: 5px;")
        self.lineEditEmployeeID.setPlaceholderText("")
        self.lineEditEmployeeID.setObjectName("lineEditEmployeeID")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBoxMenu)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonAddEmployee = QtWidgets.QPushButton(parent=self.groupBoxMenu)
        self.pushButtonAddEmployee.setGeometry(QtCore.QRect(30, 180, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddEmployee.setFont(font)
        self.pushButtonAddEmployee.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/add (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAddEmployee.setIcon(icon3)
        self.pushButtonAddEmployee.setIconSize(QtCore.QSize(25, 30))
        self.pushButtonAddEmployee.setObjectName("pushButtonAddEmployee")
        self.pushButtonUpdateEmployee = QtWidgets.QPushButton(parent=self.groupBoxMenu)
        self.pushButtonUpdateEmployee.setGeometry(QtCore.QRect(30, 250, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateEmployee.setFont(font)
        self.pushButtonUpdateEmployee.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/backup-data.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUpdateEmployee.setIcon(icon4)
        self.pushButtonUpdateEmployee.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonUpdateEmployee.setObjectName("pushButtonUpdateEmployee")
        self.pushButtonDeleteEmployee = QtWidgets.QPushButton(parent=self.groupBoxMenu)
        self.pushButtonDeleteEmployee.setGeometry(QtCore.QRect(30, 320, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteEmployee.setFont(font)
        self.pushButtonDeleteEmployee.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Phuong Nhi/Downloads/eraser.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDeleteEmployee.setIcon(icon5)
        self.pushButtonDeleteEmployee.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonDeleteEmployee.setObjectName("pushButtonDeleteEmployee")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBoxMenu)
        self.pushButtonExit.setGeometry(QtCore.QRect(130, 440, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(248, 207, 239);\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff85c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d14789;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3); /* Bóng đổ */\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon6)
        self.pushButtonExit.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.tableWidgetEmployee = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetEmployee.setGeometry(QtCore.QRect(500, 170, 991, 521))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidgetEmployee.setFont(font)
        self.tableWidgetEmployee.setObjectName("tableWidgetEmployee")
        self.tableWidgetEmployee.setColumnCount(7)
        self.tableWidgetEmployee.setRowCount(17)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setItem(0, 1, item)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 1491, 701))
        self.label_5.setStyleSheet("border-radius: 20; background: rgb(255, 255, 255)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 1531, 771))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/background.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 50, 21, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\Retail-Management-Project\\ui\\../images/profile.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.timelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(1280, 60, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.timelabel.setFont(font)
        self.timelabel.setText("")
        self.timelabel.setObjectName("timelabel")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.pushButtonLogout.raise_()
        self.label_2.raise_()
        self.groupBoxMenu.raise_()
        self.tableWidgetEmployee.raise_()
        self.label_7.raise_()
        self.timelabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Employee Management"))
        self.label.setText(_translate("MainWindow", "ADMIN"))
        self.pushButtonLogout.setText(_translate("MainWindow", "Logout"))
        self.label_2.setText(_translate("MainWindow", "Employee Management"))
        self.groupBoxMenu.setTitle(_translate("MainWindow", "Menu"))
        self.label_3.setText(_translate("MainWindow", "Employee ID:"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "Employee Options:"))
        self.pushButtonAddEmployee.setText(_translate("MainWindow", "ADD EMPLOYEE"))
        self.pushButtonUpdateEmployee.setText(_translate("MainWindow", "UPDATE EMPLOYEE"))
        self.pushButtonDeleteEmployee.setText(_translate("MainWindow", "DELETE EMPLOYEE"))
        self.pushButtonExit.setText(_translate("MainWindow", "EXIT"))
        item = self.tableWidgetEmployee.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "EMP1"))
        item = self.tableWidgetEmployee.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "EMP2"))
        item = self.tableWidgetEmployee.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "EMP3"))
        item = self.tableWidgetEmployee.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "EMP4"))
        item = self.tableWidgetEmployee.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "EMP5"))
        item = self.tableWidgetEmployee.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "EMP6"))
        item = self.tableWidgetEmployee.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "EMP7"))
        item = self.tableWidgetEmployee.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "EMP8"))
        item = self.tableWidgetEmployee.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "EMP9"))
        item = self.tableWidgetEmployee.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "EMP10"))
        item = self.tableWidgetEmployee.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "EMP11"))
        item = self.tableWidgetEmployee.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "EMP12"))
        item = self.tableWidgetEmployee.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "EMP13"))
        item = self.tableWidgetEmployee.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "EMP14"))
        item = self.tableWidgetEmployee.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "EMP15"))
        item = self.tableWidgetEmployee.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "EMP16"))
        item = self.tableWidgetEmployee.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "EMP17"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contact No."))
        item = self.tableWidgetEmployee.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "No."))
        item = self.tableWidgetEmployee.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Designation"))
        __sortingEnabled = self.tableWidgetEmployee.isSortingEnabled()
        self.tableWidgetEmployee.setSortingEnabled(False)
        self.tableWidgetEmployee.setSortingEnabled(__sortingEnabled)
